[package]
name = "maizefunge"
version = "0.1.0"
authors = ["Damian Grüner <grunerdamian@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "lib/maizeinterp",
    "lib/maizelib",
#    "bin/",
]

[dependencies]

[dev-dependencies]
maizelib = { path="lib/maizelib" }